-- ============================================================
-- WarrantyOS — Migration 001: invitations table
-- Run this in the Supabase SQL Editor after the initial schema.
-- ============================================================


-- ────────────────────────────────────────────────────────────
-- invitations
-- Holds pending invitations generated by platform admins (or
-- the CLI) when provisioning a new tenant or adding a user.
-- The invited party visits /signup?token=<token> to complete
-- their account setup. The auth.users row is NOT created at
-- provisioning time — it is created by the user on signup.
-- ────────────────────────────────────────────────────────────
create table public.invitations (
  id          uuid        primary key default gen_random_uuid(),
  tenant_id   uuid        not null references public.tenants(id) on delete cascade,
  email       text        not null,
  role        text        not null check (role in ('admin', 'reviewer', 'viewer')),
  full_name   text,
  token       text        not null unique,
  expires_at  timestamptz not null,
  consumed_at timestamptz,
  created_at  timestamptz not null default now()
);

comment on table  public.invitations             is 'Pending invitations. Token is validated at signup; auth user is created then, not at provisioning time.';
comment on column public.invitations.token       is '64-char hex string (32 random bytes). Sent in the signup URL, never stored hashed — protected by service-role-only writes and RLS.';
comment on column public.invitations.consumed_at is 'Set when the invited user completes signup. Non-null means the token is spent.';

create index invitations_tenant_id_idx on public.invitations(tenant_id);
create index invitations_token_idx     on public.invitations(token);

alter table public.invitations enable row level security;


-- ────────────────────────────────────────────────────────────
-- RLS policies: invitations
-- ────────────────────────────────────────────────────────────

-- Tenant members can see their tenant's invitations (e.g. to
-- list pending invites in a future admin UI). Writes are
-- service-role only — invitation lifecycle is a platform op.
create policy "invitations: members can view their tenant's invitations"
  on public.invitations
  for select
  using (tenant_id = public.get_user_tenant_id());


-- ────────────────────────────────────────────────────────────
-- Grants
-- ────────────────────────────────────────────────────────────
grant all on public.invitations to anon, authenticated, service_role;
